### PR TITLE
Updated to WE 7.0 and required Y

### PR DESCRIPTION
**Pull request by AnonymousDr**
[!] Updated to WorldEdit 7.0 version
[+] Now this plugin requires Ymin and Ymax to spawn.

### CODE REVIEW

**Comment by ryandw11** [comment]
Hello, thank you for contributing to the code. I have some questions.
1. Has this version been tested?
2. Is there a specific reason why the config.yml and plugin.yml was moved to inside the src folder?
3. Is the code for the Ymin and Ymax programmed in? I am having a hard time finding the code for it.

**Comment by wyatt-herkamp** [comment]
A. Don't store the resources in /src it should be stored in /src/resources/ or in the base.  I personally do /src/resources/
B. Show proof of it working. 
I also want to know why are you modifying resource folder location?

**Comment by AnonymousDr** [comment]
image
Yes, I've tested it, the structures are the bedrock. If do you want you can change the src folder, my IDE works with this way by default. The Ymin and Ymax are in Structures class.

Sorry for the late response.

**Review by ryandw11 — APPROVED** [review]

**Comment by ryandw11** [comment]
Thank you for your contributions to the project!

**Pull request merged**
