### PR TITLE
Feature chest loot and mob spawning

### PR DESCRIPTION
**Pull request by Chusca**
This PR adds two new features to the plugin:

- **LootTables to containers**: admins can create them through config files. Everytime a structure is spawned the plugin will search for all the containers (chests, brewingstands, furnaces, ...) and fill them with the loottable content.
- **Mob spawning**: admins can create spawnpoints for mobs using signs. The code ads support for MythicMobs so they can add more difficulty to the structures. 
Every Sign need two lines:
     1. The first line indicates if it is a Vanilla or a MythicMobs mob
     2. The second line indicates the Type/Name of the mob to spawn

     photo_2019-07-18_15-44-13
     photo_2019-07-18_15-44-18
 
PS: Let me know if you need more information!

### CODE REVIEW

**Comment by ryandw11** [comment]
Amazing. I will get someone to help check the code over with me. Will get this merged as soon as possible.

**Comment by ryandw11** [comment]
Has this been tested at all? Having trouble getting it to work.

**Comment by Chusca** [comment]
> Has this been tested at all? Having trouble getting it to work.

Yes, I have tested it myself, need any help?

**Comment by ryandw11** [comment]
Using the [mob] sign does not seem to work. Also structures seem to no longer be spawning for some reason.

**Comment by Chusca** [comment]
Thats weird... I'll do some testing right now

**Comment by ryandw11** [comment]
Found the issue. Silly error on my part. Works great. Thanks for contributing to the project. It will be released in the next update (1.4.2) after a few more features are finished.

**Comment by Chusca** [comment]
Good! 
If you find something weird or wrong don't hesitate to contact me

**Comment by ryandw11** [comment]
I added in random rotation (all by 90deg) and the signs/chest stopped working. I don't see why though because looking at your code it seems to grab the locations after the schematic was placed so I don't see why it would stop working.

**Comment by Chusca** [comment]
Mmmh, thats weird... but I think it can be related with the [offset calculation](https://github.com/ryandw11/CustomStructures/blob/c5728594f8003ebb9c6524af25522143d84148ae/src/com/ryandw11/structure/SchematicHandeler.java#L133), I had to calculate where one of the bottom corners of the structure is in the world in order to loop through it. 
Maybe we need to calculate the offset with the rotation in mind too?

**Comment by ryandw11** [comment]
Yea. I am doing this to the minimum and the offset. I don't if I need to change the width, height, and length though.
```java
private BlockVector3 rotateY(BlockVector3 bv, int theta) {
		BlockVector3 offset = bv;
		return BlockVector3.at((offset.getX() * Math.cos(theta)) + (offset.getZ() * Math.sin(theta)), 
				offset.getY(), 
				(-offset.getX() * Math.sin(theta)) + (offset.getZ() * Math.cos(theta)));
	}
```

**Comment by Chusca** [comment]
I think width, height and length should stay the same and maybe minimum and origin too because they are being obtained from the clipboard and the clipboard has being transformed and rotated. So probably those coordinates are ok. Maybe we just need to do some math in order to calculate right the offset

**Comment by Chusca** [comment]
Is it all the code pushed in the 1.4.2 branch? I can do some testing in my end too

**Comment by ryandw11** [comment]
Yes. All of the code is in the 1.4.2 branch.

**Comment by Chusca** [comment]
Cool let my do some testing

**Comment by ryandw11** [comment]
```
| x cos θ + z sin θ |
|        y          |
|-x sin θ + z cos θ |
```
This is the matrix for a 3d rotation on the y-axis. I tested doing it on the offset with little result.

**Comment by Chusca** [comment]
Ok, I was totally wrong in assuming that transforming the clipboard would also transform the origin and the minimum coordinates...
I ran some tests and found this:
```
[00:25:04 WARN]: [CustomStructures] rotY: 180
[00:25:04 WARN]: [CustomStructures] minimum: (98, 91, -85)
[00:25:04 WARN]: [CustomStructures] origin: (97, 91, -84)
[00:25:04 WARN]: [CustomStructures] offset: (-1, 0, 1)
[00:25:04 WARN]: [CustomStructures] pasteLocation: Location{world=CraftWorld{name=world},x=96.0,y=73.0,z=768.0,pitch=0.0,yaw=0.0}

[00:26:04 WARN]: [CustomStructures] rotY: 270
[00:26:06 WARN]: [CustomStructures] minimum: (98, 91, -85)
[00:26:06 WARN]: [CustomStructures] origin: (97, 91, -84)
[00:26:06 WARN]: [CustomStructures] offset: (-1, 0, 1)
[00:26:06 WARN]: [CustomStructures] pasteLocation: Location{world=CraftWorld{name=world},x=176.0,y=66.0,z=1088.0,pitch=0.0,yaw=0.0}

[00:26:06 WARN]: [CustomStructures] rotY: 0
[00:26:06 WARN]: [CustomStructures] minimum: (98, 91, -85)
[00:26:06 WARN]: [CustomStructures] origin: (97, 91, -84)
[00:26:06 WARN]: [CustomStructures] offset: (-1, 0, 1)
[00:26:06 WARN]: [CustomStructures] pasteLocation: Location{world=CraftWorld{name=world},x=64.0,y=71.0,z=1056.0,pitch=0.0,yaw=0.0}
```
Minimum and origin stay the same so offset is always the same too. Since origin is the coordinate where the schematic was originally copied (and the reference that will be used to paste it too) I think (If im not wrong now again) we just need to fix (rotate?) minimum

**Comment by ryandw11** [comment]
Yea rotating the minimum might do it. I still believe the width and length would make a difference since the schematic could be a rectangle. That would be easy though as you would just swap the length and width.

**Comment by Chusca** [comment]
I have managed to kinda make it work just rotating the minimum coordinates using origin as reference point...

```java
private BlockVector3 blockVector3Rotate(BlockVector3 minimum, BlockVector3 origin, double radians) {
		double sin = Math.sin(radians);
		double cos = Math.cos(radians);

		// rotate point
		double newX = cos * (minimum.getX() - origin.getX()) - sin * (minimum.getZ() - origin.getZ()) + origin.getX();
		double newZ = sin * (minimum.getX() - origin.getX()) + cos * (minimum.getZ() - origin.getZ()) + origin.getZ();

		return BlockVector3.at(newX, minimum.getY(), newZ);
	}
```

But, as you can see here, it just works with 0 degrees (obviously) and 270.

```
[09:41:39 WARN]: [CustomStructures] rotY: 0
[09:41:39 WARN]: [CustomStructures] minimum: (98, 91, -85)
[09:41:39 WARN]: [CustomStructures] rotatedMinimum(98, 91, -85)
[09:41:39 WARN]: [CustomStructures] origin: (97, 91, -84)
[09:41:39 WARN]: [CustomStructures] offset: (-1, 0, 1)
[09:41:39 WARN]: [CustomStructures] foundAnyChest? true

[09:42:49 WARN]: [CustomStructures] rotY: 90
[09:42:49 WARN]: [CustomStructures] minimum: (98, 91, -85)
[09:42:49 WARN]: [CustomStructures] rotatedMinimum(98, 91, -83)
[09:42:49 WARN]: [CustomStructures] origin: (97, 91, -84)
[09:42:49 WARN]: [CustomStructures] offset: (-1, 0, -1)
[09:42:49 WARN]: [CustomStructures] foundAnyChest? false

[09:42:57 WARN]: [CustomStructures] rotY: 180
[09:42:57 WARN]: [CustomStructures] minimum: (98, 91, -85)
[09:42:57 WARN]: [CustomStructures] rotatedMinimum(96, 91, -83)
[09:42:57 WARN]: [CustomStructures] origin: (97, 91, -84)
[09:42:57 WARN]: [CustomStructures] offset: (1, 0, -1)
[09:42:57 WARN]: [CustomStructures] foundAnyChest? false

[09:43:01 WARN]: [CustomStructures] rotY: 270
[09:43:01 WARN]: [CustomStructures] minimum: (98, 91, -85)
[09:43:01 WARN]: [CustomStructures] rotatedMinimum(96, 91, -85)
[09:43:01 WARN]: [CustomStructures] origin: (97, 91, -84)
[09:43:01 WARN]: [CustomStructures] offset: (1, 0, 1)
[09:43:01 WARN]: [CustomStructures] foundAnyChest? true
```

I think we are close to the solution

PS: I agree with you, we probably need to swap length and width too

**Comment by ryandw11** [comment]
Are you using the minimum rotated to calculate the offset?

**Comment by Chusca** [comment]
Yes im using blockVector3Rotate to rotate the minimum and then calculate the offset

```java
private List<Location> getContainersAndSignsLocations(Clipboard clipboard, Location pasteLocation, int rotation) {

		BlockVector3 minimum = clipboard.getRegion().getMinimumPoint();
		BlockVector3 origin = clipboard.getOrigin();
		// Rotating the minimum around origin point
		BlockVector3 rotatedMinimum = blockVector3Rotate(minimum, origin, Math.toRadians(rotation));
		BlockVector3 offset = origin.subtract(rotatedMinimum);
// {...} 
}
```
Since we are rotating points, the coordinates of the offset can take positive and negative values. I think we need to be sure if we have to add or subtract that offset to the location we are using to look for chests / signs

PS: I still think that if length != width (is a rectangle) we need to swap them

**Comment by ryandw11** [comment]
All of my minimums and rotated minimums hover around the same point no matter where the schematic spawns... With the length/with swap we only need to do it when the rotation angle is 90 or 270 degrees as 180 is just a flip.

Edit: I am just going to release the plugin now and just classify it as a bug that way users who are waiting for this update don't have to wait for much longer.

**Pull request merged**
