### PR TITLE
Fix structures attempting to spawn above y=255

### PR DESCRIPTION
**Pull request by Iniquit**
Prevent structures from attempting to spawn above y=255 by fixing the bounded random number generation used in HandleY.java for determining structure Y. Addresses #33.

### CODE REVIEW

**Comment by ryandw11** [comment]
While this code did change to use better practices, the code does not fix the problem stated above.

**Comment by Iniquit** [comment]
Hi,

Did you test it? This resolved the problem for me locally while using the same 100-200 height range as specified in #33. While I did use ThreadLocalRandom.current(), the real change is in the nextInt method:

The original returns a random integer between `num2 + 1` and 0, plus `num1`:
`nextInt(num2 + 1) + num1;`
In cases where num1 and num2 are both large, as with 100 & 200, this version could pick say, 190 randomly and then add num1 (100) to it, exceeding the 255 height limit.

The new version returns a random integer between `num1` and `num2 +1`:
`nextInt(num1, num2 + 1);`
Because this version only picks an integer between the given min and max value, it will never exceed 255 unless the user intentionally enters a higher value in config.

**Comment by ryandw11** [comment]
Oh yea, I see that now. I'll go ahead and accept this one too.

**Comment by Iniquit** [comment]
Awesome, thanks!

**Pull request merged**
